// <auto-generated />
using Demo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Demo.Data.Migrations
{
    [DbContext(typeof(DemoDataContext))]
    [Migration("20200315111131_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("Demo.Data.Contact", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CellPhone")
                        .HasMaxLength(128);

                    b.Property<string>("Email")
                        .HasMaxLength(128);

                    b.Property<string>("FirstName")
                        .HasMaxLength(128);

                    b.Property<string>("LastName")
                        .HasMaxLength(128);

                    b.HasKey("Id");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("Demo.Data.NoteWithFulltext", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Note")
                        .HasMaxLength(2048);

                    b.Property<string>("Topic")
                        .HasMaxLength(512);

                    b.HasKey("Id");

                    b.ToTable("NotesWithFullText");
                });

            modelBuilder.Entity("Demo.Data.NoteWithoutFulltext", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Note")
                        .HasMaxLength(2048);

                    b.Property<string>("Topic")
                        .HasMaxLength(512);

                    b.HasKey("Id");

                    b.HasIndex("Topic");

                    b.ToTable("NotesWithoutFulltext");
                });
#pragma warning restore 612, 618
        }
    }
}
